#TODO: Provide instructions for modpack devs.
---
ModPackConfigName: null
ModPackConfigVersion: 0
ShowOTGWorldCreationMenu: true
version: 1
WorldName: "Moon"
Overworld:
  PresetName: "Moon"
  DimensionId: 0
  ShowInWorldCreationGUI: true
  Seed: ""
  GameType: "Creative"
  BonusChest: false
  AllowCheats: true
  WorldBorderRadiusInChunks: 0
  PregeneratorRadiusInChunks: 0
  Settings:
    DimensionPortalMaterials:
    - "PRISMARINE:2"
    PortalColor: "default"
    PortalParticleType: "portal"
    PortalMobType: "zombie_pigman"
    PortalMobSpawnChance: 2000
    IsOTGPlus: false
    DimensionBelow: "Skylands"
    DimensionAbove: ""
    DimensionBelowHeight: 0
    DimensionAboveHeight: 256
    TeleportToSpawnOnly: true
    WelcomeMessage: ""
    DepartMessage: ""
    HasSkyLight: true
    IsSurfaceWorld: true
    CanRespawnHere: true
    DoesWaterVaporize: false
    DoesXZShowFog: false
    UseCustomFogColor: false
    FogColorRed: 0.20000000298023224
    FogColorGreen: 0.029999999329447746
    FogColorBlue: 0.029999999329447746
    IsSkyColored: true
    CloudHeight: 16
    CanDoLightning: true
    CanDoRainSnowIce: true
    IsNightWorld: true
    VoidFogYFactor: 0.03125
    GravityFactor: 0.08
    ShouldMapSpin: true
    CanDropChunk: true
    RespawnDimension: 0
    MovementFactor: 1
    ItemsToAddOnJoinDimension: ""
    ItemsToRemoveOnJoinDimension: ""
    ItemsToAddOnLeaveDimension: ""
    ItemsToRemoveOnLeaveDimension: ""
    ItemsToAddOnRespawn: ""
    SpawnPointSet: true
    SpawnPointX: 543
    SpawnPointY: 59
    SpawnPointZ: 1039
    PlayersCanBreakBlocks: true
    ExplosionsCanBreakBlocks: true
    PlayersCanPlaceBlocks: true
  GameRules:
    CommandBlockOutput: true
    DisableElytraMovementCheck: false
    DoDaylightCycle: false
    DoEntityDrops: true
    DoFireTick: true
    DoLimitedCrafting: false
    DoMobLoot: true
    DoMobSpawning: false
    DoTileDrops: true
    DoWeatherCycle: false
    GameLoopFunction: true
    KeepInventory: false
    LogAdminCommands: true
    MaxCommandChainLength: 65536
    MaxEntityCramming: 24
    MobGriefing: true
    NaturalRegeneration: true
    RandomTickSpeed: 3
    ReducedDebugInfo: false
    SendCommandFeedback: true
    ShowDeathMessages: true
    SpawnRadius: 1
    SpectatorsGenerateChunks: true
Dimensions: []